### ISSUE TITLE
Issue with ajax and run.php line 48

### ISSUE THREAD

**Issue by createco** [delcroip/dolibarr_reportico#1]
I've installed and activated and installed reportico as well.  Any help to resolve would be appreciated.  Also, have you created any templates? 

Warning: include(run.php): failed to open stream: No such file or directory in /home/gocreate/public_html/erp/htdocs/reportico/run_ajax.php on line 48

Warning: include(run.php): failed to open stream: No such file or directory in /home/gocreate/public_html/erp/htdocs/reportico/run_ajax.php on line 48

Warning: include(): Failed opening 'run.php' for inclusion (include_path='/home/gocreate/public_html/htdocs') in /home/gocreate/public_html/erp/htdocs/reportico/run_ajax.php on line 48

**Comment by delcroip** [comment]
hello,
It's still in development I encounter issue to hide the db parameters (and I don't have time to code this days) but you can run reportico in standalone mode copying the folder reportico( not dolibarr_reportico) in a place accessible remotely ( in htdocs for instance).

there is also a module based on reportico 2report but it's not free ( and doesn't give any credit the the reportico developers)

Best regards

**Comment by createco** [comment]
Presh, exactly what I needed to k ow

**Comment by delcroip** [comment]
I push a new branch called simple that only show reportico in the dolibarr frame but without further integration.

Dolibarr module is available here:https://ide.pmpd.eu/dolibarr/build/module_reportico-.4.3.zip

Br.
